---
new_page_extension: md
auto_deploy: false
admin_path: admin
webhook_url: 'https://api.stackbit.com/project/6026f0232f4a480016fdbf1c/webhook/forestry'
sections:
- type: document
  path: _config.yml
  label: Site Configuration
  templates:
  - config
- type: directory
  path: _data/authors
  label: Person
  create: all
  match: '**/*'
  new_doc_ext: yaml
  templates:
  - person
- type: document
  path: blog/index.md
  label: Blog
  templates:
  - blog
- type: jekyll-pages
  label: Pages
  create: all
  exclude: '{README.md,LICENSE.md}'
  new_doc_ext: md
  templates:
  - landing
  - page
  - post
upload_dir: images
public_path: /images
front_matter_path: ''
use_front_matter_path: false
file_template: ':filename:'
